### PR TITLE
added pmss for spacy gpu preference check

### PR DESCRIPTION
**Pull request by bradley-erickson**
TODO: this still needs testing for the GPU usage. Passing it over to an NCSU student.
My GPU is Cuda version 12.5 and the Spacy version on the system is 3.3. This Spacy version does not support Cuda 12.5.

### CODE REVIEW

**Comment by bradley-erickson** [comment]
Fixes #161

**Comment by bradley-erickson** [comment]
Waiting on @duckduckdoof to test and make sure it works.

**Comment by duckduckdoof** [comment]
Trying to get a new install of WO working with updated AWE module (with spacy 3.5.4); there is only one dependency conflict after installing AWE modules:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dash-extensions 1.0.18 requires pydantic<3.0.0,>=2.7.1, but you have pydantic 1.10.18 which is incompatible.
```

Will still be checking if spacy/cuda pmss works.

**Comment by duckduckdoof** [comment]
Had to install WO and point to Arglab versions of components, lexica, languagetool, and spellcorrect.

Finally got WO working with spacy+cupy gpu settings (ran awe_nlp.py main); this works for `process_text()` but not for multithreading functions such as `process_texts_parallel()`.

This issue https://github.com/explosion/spaCy/issues/5507 references that it is a known issue regarding trying to get spacy gpu/cupy stuff working with multithreading.

**Pull request merged**
